schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "sweep_modifier_lite"
version = "2.0.1"
name = "Sweep Modifier"
tagline = "Adds a Sweep Modifier with profile and bevel curve support using Geometry Nodes"
maintainer = "Abbos Mirzaev <mirzaev3d@gmail.com>"
# Supported types: "add-on", "theme"
type = "add-on"

# # Optional: link to documentation, support, source files, etc
# website = "https://extensions.blender.org/add-ons/my-example-package/"

# # Optional: tag list defined by Blender and server, see:
# # https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
# tags = ["Animation", "Sequencer"]

blender_version_min = "4.4.0"
# # Optional: Blender version that the extension does not support, earlier versions are supported.
# # This can be omitted and defined later on the extensions platform if an issue is found.
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]
# # Optional: required by some licenses.
copyright = [
   "2025 Abbos Mirzaev",
   "2021 M3D",
]